image: python:3.10

stages:
  - deploy

before_script:
  - python -m pip install --upgrade pip
  #- pip install -r requirements.txt
  - pip install sphinx sphinx-autodoc sphinx_rtd_theme

pages:
  stage: deploy
  script:
    - sphinx-build -b html docs/source/ public/
  artifacts:
    paths:
      - public
  only:
    - main
