image: python:3.9

stages:
  - build
  - deploy

before_script:
  - python -m pip install --upgrade pip
  #- pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme

build_docs:
  stage: build
  script:
    - sphinx-build -b html docs/source/ public/
  artifacts:
    paths:
      - public
  only:
    - main

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - main