image: python:3.10

stages:
  - deploy

before_script:
  - python -m pip install --upgrade pip
  #- pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme

pages:
  stage: deploy
  script:
    - cd docs/ && make html
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - main
